### ISSUE TITLE
`401` error when getting imageDetails in Manager

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/runtime#2026]
```
  ✗  ERROR:  error getting signature for image foo/bar:baz: HEAD https://foobar.dkr.ecr.us-east-2.amazonaws.com/v2/acorn/foo/bar/manifests/sha256-ad36c36a6ca075eda5a8758e5d6ec85724d4e739aba6c9eb7c72263fb4fd7db6.sig: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)
  ```
  
  Slack thread: https://acorn-io.slack.com/archives/C03FU91U4SX/p1691177374735949

**Comment by sangee2004** [comment]
Tested on `beta`

Able to get image details successfully  for both local and remote images that are signed.

`acorn image details <image-name>` fetches the signature details in `signatureDigest`  field.


Local image:

```
 acorn image sign  mytestnew --key ~/santest3.key -a qatag=ok
  •  Signing Image mytestnew (digest: index.docker.io/library/mytestnew@sha256:7a567c1f23887d340d0a30737c66d01d735e494116abbe0a8c19eb3ea5ec07be) using key /Users/sangeethahariharan/santest3.key
? Enter password for private key /Users/sangeethahariharan/santest3.key: ********
  ✔  Done: Pushed signature sha256:14037cebdd2dc1762d1d98d8db8a6ab73e2118c58ac437b8b7196dd8adcf6490
sangeethahariharan@Sangeethas-MacBook-Pro example1 % acorn images
REPOSITORY   TAG       IMAGE-ID
mytestnew    latest    7a567c1f2388
sangeethahariharan@Sangeethas-MacBook-Pro example1 % acorn image details mytestnew                               
---
items:
- appImage:
    acornfile: "args: {\n\tnewApp:  true\n\toldtext: \"old\"\n\tnewtext: \"v17\"\n}\ncontainers:
      {\n\tmyweb: {\n\timage: \"nginx\"\n\tports: publish: \"80/http\"\n\tfiles: {\n\t\t\"/usr/share/nginx/html/index.html\":
      std.ifelse(args.newApp, args.newtext, args.oldtext)\n\t\t\"/usr/share/nginx/html/test.html\":
      \ \"test1\"\n\t\t\"/usr/share/nginx/html/test2.html\": \"test2\"\n\t}\n}\n}\n"
    digest: sha256:7a567c1f23887d340d0a30737c66d01d735e494116abbe0a8c19eb3ea5ec07be
    id: 7a567c1f23887d340d0a30737c66d01d735e494116abbe0a8c19eb3ea5ec07be
    imageData:
      builds:
      - containerBuild:
          image: nginx
        imageKey: myweb
      containers:
        myweb:
          image: sha256:6f564bf91b24835dde45e1a3c68cfec829385efb613eab2e6f6774ee2031c238
    vcs: {}
  appSpec:
    containers:
      myweb:
        files:
          /usr/share/nginx/html/index.html:
            content: djE3
            mode: "0644"
            secret: {}
          /usr/share/nginx/html/test.html:
            content: dGVzdDE=
            mode: "0644"
            secret: {}
          /usr/share/nginx/html/test2.html:
            content: dGVzdDI=
            mode: "0644"
            secret: {}
        image: nginx
        metrics: {}
        permissions: {}
        ports:
        - protocol: http
          publish: true
          targetPort: 80
        probes: null
  imageName: 7a567c1f23887d340d0a30737c66d01d735e494116abbe0a8c19eb3ea5ec07be
  params:
    params:
    - name: newApp
      schema: '*true | bool'
      type: bool
    - name: oldtext
      schema: '*"old" | string'
      type: string
    - name: newtext
      schema: '*"v17" | string'
      type: string
  signatureDigest: sha256:c1c938990d1aeb23ba95f94270c2a211aaad196f6d96c14047eea91c26a3585b
```

Remote image that is signed:

```
acorn images details sangeetha/myfirstacorn:v0.0.4
---
items:
- appImage:
    acornfile: "args: {\n\tnewApp:  true\n\toldtext: \"old\"\n\tnewtext: \"v0.0.4\"\n}\ncontainers:
      myweb1: {\n\timage: \"nginx\"\n\tports: publish: \"80/http\"\n\tfiles: {\n\"/usr/share/nginx/html/index.html\":
      std.ifelse(args.newApp, args.newtext, args.oldtext)\n\"/usr/share/nginx/html/test.html\":
      \"test\"\n\"/usr/share/nginx/html/test2.html\": \"test2\"\n\t}\n}\n"
    digest: sha256:a6e655dab6d39796d297a1b8445c549594ae19a5874e1edb287622490df41833
    id: index.docker.io/sangeetha/myfirstacorn:v0.0.4
    imageData:
      builds:
      - containerBuild:
          image: nginx
        imageKey: myweb1
      containers:
        myweb1:
          image: sha256:aadf2b5aa4ea56998e3cdc5afa5fd848822838181032f3c2dbc7d436ce298b3e
    vcs: {}
  appSpec:
    containers:
      myweb1:
        files:
          /usr/share/nginx/html/index.html:
            content: djAuMC40
            mode: "0644"
            secret: {}
          /usr/share/nginx/html/test.html:
            content: dGVzdA==
            mode: "0644"
            secret: {}
          /usr/share/nginx/html/test2.html:
            content: dGVzdDI=
            mode: "0644"
            secret: {}
        image: nginx
        metrics: {}
        permissions: {}
        ports:
        - protocol: http
          publish: true
          targetPort: 80
        probes: null
  imageName: sangeetha/myfirstacorn:v0.0.4
  params:
    params:
    - name: newApp
      schema: '*true | bool'
      type: bool
    - name: oldtext
      schema: '*"old" | string'
      type: string
    - name: newtext
      schema: '*"v0.0.4" | string'
      type: string
  signatureDigest: sha256:3aaf1bda301df3529f440ebb2c03e7b33d779fc5198ca5f1b2acaff0d1daf53a

```
