### ISSUE TITLE
acorn logout with no sever parameters does not work when there is only 1 sever we are currently logged into.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#2090]
**acorn version** - `v0.8.0-rc4-29-g6a019fe7+6a019fe7`

**Steps to reproduce the problem:**
1. Use `acorn login <server1>` to login .

Configuration file after log in:
```
cat ~/Library/Application\ Support/acorn/config.yaml
acornConfig: /Users/sangeethahariharan/Library/Application Support/acorn/config.yaml
acornServers:
- server1
auths:
  server:
    auth: ***
currentProject: <server1>/<account>/<project>
```
 3.  Use `acorn logout` without any parameters.
 ```
 % acorn logout                                        
  ✗  ERROR:  accepts 1 arg(s), received 0
```
**Expected Behavior:**
We expect to be logged out of <server1> since it is the only server.
