### ISSUE TITLE
Add "resources" field to the computeClass definition

### ISSUE THREAD

**Issue by dciangot** [acorn-io/runtime#2380]
Introducing the field resources to the [ProjectComputeClassInstance](https://github.com/acorn-io/runtime/blob/main/pkg/apis/internal.admin.acorn.io/v1/computeclasses.go#L44) and, as a consequence, to [ClusterComputeClassInstance](https://github.com/acorn-io/runtime/blob/main/pkg/apis/internal.admin.acorn.io/v1/computeclasses.go#L13) will enable cluster admins to add GPU and any custom hardware to the "offering" for the users.

Note from Darren: _"One catch is that the resources can only be applied to the "main container" not any sidecars, as you really don't know which one to apply to."_
Complete discussion ref on [slack](https://acorn-users.slack.com/archives/C03R9ME0SKC/p1702567598185389)

**Comment by sangee2004** [comment]
Tested with acorn version - `v0.10.0-rc2-9-g43dbcbf4+43dbcbf4`

1. Able to create a computeclass with `resources` field containing `requests` and `limits` using following yaml :
```
kind: ClusterComputeClass
apiVersion: admin.acorn.io/v1
default: false
metadata:
  name: cc-res
description: Large compute for linux on arm64
cpuScaler: 0.75
supportedRegions:
 - local
memory:
  default: 20M
  min: 10M
  max: 100M
resources:
  limits:
    gpu-vendor.example/example-gpu: 2
  requests:
    gpu-vendor.example/example-gpu: 2
``` 

2. When deploying app using this compute class , I am able to see the pods having the resources set in the container spec as follows:
```
                        "resources": {
                            "limits": {
                                "gpu-vendor.example/example-gpu": "2",
                                "memory": "20M"
                            },
                            "requests": {
                                "cpu": "14m",
                                "gpu-vendor.example/example-gpu": "2",
                                "memory": "20M"
                            }
                        },
```

The app deployment itself fails in my case with following error since I dont have an environment that has nodes that support gpu which is as expected.
  
```
0/1 nodes are available: 1 Insufficient gpu-vendor.example/example-gpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod
```
