### ISSUE TITLE
Add ability to create functional basic secrets from cli

### ISSUE THREAD

**Issue by cjellick** [acorn-io/runtime#347]
```
acorn secrets create --type basic my-secret
```
should create a functional basic secret with username and password set, but instead its an empty secret with no keys.

In reality, I was trying to figure out the k8s yaml for generating a secret so that I could generate this secret in fleet and use it in two different (gitops created) acorn apps.

So, I also want `kubectl create -f secret.yaml` to work where secret.yaml is
```
apiVersion: api.acorn.io/v1
kind: Secret
metadata:
  name: staging-db-user-credentials2
  namespace: acorn
type: basic
```
