### ISSUE TITLE
Pending on Ingress

### ISSUE THREAD

**Issue by mreferre** [acorn-io/runtime#577]
Hey folks. I am trying to deploy [my standard test app](https://github.com/mreferre/yelb) with Acorn and I am failing to see the Ingress to stabilize (err .. work at all). 

I am using an EKS cluster (1.21) with the AWS LB Controller. 

I know the controller works because if I deploy my K8s YAML file it works just fine. This is the (pretty verbose) YAML I am using (also available [here](https://github.com/mreferre/yelb/blob/master/deployments/platformdeployment/Kubernetes/yaml/yelb-k8s-ingress-alb-ip.yaml) in the repo): 

```
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis-server
    tier: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: redis-server
    tier: cache
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-db
  labels:
    app: yelb-db
    tier: backenddb
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: yelb-db
    tier: backenddb
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-appserver
  labels:
    app: yelb-appserver
    tier: middletier
spec:
  type: ClusterIP
  ports:
  - port: 4567
  selector:
    app: yelb-appserver
    tier: middletier
---
apiVersion: v1
kind: Service
metadata:
  name: yelb-ui
  labels:
    app: yelb-ui
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: yelb-ui
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "yelb-ui"
  annotations:
    kubernetes.io/ingress.class: alb # check this, your ingress.class may be different 
    alb.ingress.kubernetes.io/scheme: internet-facing 
    alb.ingress.kubernetes.io/target-type: ip 
  labels:
    app: "yelb-ui"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "yelb-ui"
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-ui
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: yelb-ui
      tier: frontend    
  template:
    metadata:
      labels:
        app: yelb-ui
        tier: frontend
    spec:
      containers:
      - name: yelb-ui
        image:  mreferre/yelb-ui:0.7
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: redis-server
      tier: cache
  template:
    metadata:
      labels:
        app: redis-server
        tier: cache
    spec:
      containers:
      - name: redis-server
        image: redis:4.0.2
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-db
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: yelb-db
      tier: backenddb
  template:
    metadata:
      labels:
        app: yelb-db
        tier: backenddb
    spec:
      containers:
      - name: yelb-db
        image:  mreferre/yelb-db:0.5
        ports:
        - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-appserver
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: yelb-appserver
      tier: middletier
  template:
    metadata:
      labels:
        app: yelb-appserver
        tier: middletier
    spec:
      containers:
      - name: yelb-appserver
        image:  mreferre/yelb-appserver:0.5
        ports:
        - containerPort: 4567
```

This is the `Acornfile` I am trying to shape off of the above: 

```
args: {
  scale_ui: 2
  scale_appserver: 3
}

containers: {
  "yelb-ui": {
      image: "mreferre/yelb-ui:0.7"
      scale: args.scale_ui
      ports: 
        publish: "80/http"
      dependsOn: "yelb-appserver"
      }
  "yelb-appserver": {
      image: "mreferre/yelb-appserver:0.5"
      scale: args.scale_appserver
      ports: "4567/tcp"
      dependsOn: [
        "redis-server",
        "yelb-db"
      ]
  }
  "redis-server": {
      image: "redis:4.0.2"
      ports: "6379/tcp"
  }
  "yelb-db": {
      image: "mreferre/yelb-db:0.5"
      ports: "5432/tcp"
  }
}
```

The stack seems to come up fine and all containers in the Acorn seem operational but I fail to see the Ingress being configured. This is how the two ingresses look like (one for the "native YAML" and one from the `Acornfile`): 

```
$ kubectl get ingress -A                                                                                          
NAMESPACE                 NAME      CLASS    HOSTS                                         ADDRESS                                                                PORTS   AGE
default                   yelb-ui   <none>   *                                             k8s-default-yelbui-9a80765730-1696724264.us-west-2.elb.amazonaws.com   80      8m7s
red-flower-1efda903-e8c   yelb-ui   <none>   yelb-ui.red-flower.pm64pd.alpha.on-acorn.io                                                                          80      104m
$
```  

Am I doing something wrong in the `Acornfile`?

**Comment by cjellick** [comment]
Can you give us the output of `kubectl get ingress -A -o yaml`? I want to compare the yaml for the two ingresses.

**Comment by cjellick** [comment]
The fact that you got as far as you did means nothing is wrong with your acornfile. It created a proper ingress resource:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "yelb-ui"
  annotations:
    kubernetes.io/ingress.class: alb # check this, your ingress.class may be different 
    alb.ingress.kubernetes.io/scheme: internet-facing 
    alb.ingress.kubernetes.io/target-type: ip 
  labels:
    app: "yelb-ui"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "yelb-ui"
              servicePort: 80
```
...but that should have a status field with a loadbalancer object. The fact that it doesn't means that the ingress controller isn't picking it up.

Normally, I would suspect you need to set the ingress class via:
```
acorn install --ingress-class-name alb
```
but your function ingress in the default namespace doesnt have a class set either. So that's why I want to compare the two. I **suspect** it has some annotations set on it that is allowing your ingress controller to pick it up.

**Comment by cjellick** [comment]
Oooh, my bad, I misread your original post. That ingress is from your working version.

Everything still holds true except this part:
```
The fact that you got as far as you did means nothing is wrong with your acornfile. It created a proper ingress resource:
```

Can you still share the yaml output of both ingresses? I'm fairly certain it is going to be the abscense of these annotations:
```
  annotations:
    kubernetes.io/ingress.class: alb # check this, your ingress.class may be different 
    alb.ingress.kubernetes.io/scheme: internet-facing 
    alb.ingress.kubernetes.io/target-type: ip 
```
